# This is a basic workflow to help you get started with Actions

name: CI
permissions:
  id-token: write
  contents: read
  
# Controls when the workflow will run
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install
        run: yarn
      
      - name: Build
        run: yarn build

      - name: Unit Tests
        run: yarn test

      - name: E2E Tests
        run: yarn test:e2e
      
      - name: Configure AWS access
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::530798195059:role/tng-curriculum-cicd-playground-deployment-test-role
          aws-region: us-east-1
          audience: sts.amazonaws.com
          role-session-name: cicd-playground-deployment

      - name: Provision
        working-directory: ./infrastructure
        run: |
          yarn
          yarn build
          yarn cdk deploy --require-approval never --context instanceName=${GITHUB_REF_NAME}

      - name: Deploy
        run: aws s3 cp ./public s3://cicd-workshop-playground-${GITHUB_REF_NAME} --recursive