# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install
        run: yarn
      
      - name: Build
        run: yarn build

      - name: Unit Tests
        run: yarn test

      - name: E2E Tests
        run: yarn test:e2e
      
      - name: Configure AWS access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
        
      - name: Provision
        working-directory: ./infrastructure
        run: |
          yarn
          yarn build
          yarn cdk deploy --require-approval never --context instanceName=${GITHUB_REF_NAME}

      - name: Deploy
        run: aws s3 cp ./public s3://cicd-workshop-playground-${GITHUB_REF_NAME} --recursive